# This is the input to Dependabot CLI.
# For more examples of what you can do, see the smoke tests: https://github.com/dependabot/smoke-tests/tree/main/tests

job:
  # this is the directory defined in dependabot-core for the ecosystem
  package-manager: maven
  allowed-updates:
    - dependency-type: direct
      update-type: security_updates_only
  security-updates-only: false
  source:
    provider: github
    repo: raanand-hw/java-sdk
    # looks absolute, but this is relative to the root of the repo
    directory: /
    branch: master
  dependency-groups:
    - name: maven_pkgs
      rules:
        patterns:
          - org.springframework.boot:spring-boot
          
